import localFont from "next/font/local";
import { Orbitron, Inconsolata } from "next/font/google";
import "./globals.css";

const orbitron = Orbitron({subsets:["latin"], variable:"--font-orbitron"});
const inconsolata = Inconsolata({subsets:["latin"], variable:"--font-inconsolata"})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${inconsolata.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
